baseURL = 'https://patrikkoptik.de'
languageCode = 'de-de'
title = 'Patrik Koptik'
theme = 'FixIt'
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

[params]
  version = "0.3.X"
  [params.home]
    section = "none"
    showItems = false
    [params.home.profile]
      enable = true
      title = "Patrik Koptik"
      subtitle = "Cloud Native & Platform Engineer | Kubernetes Enthusiast"
      typeit = true
      social = true

  [params.social]
    GitHub = "PatrikKoptik"
    Linkedin = "patrik-koptik-27a165258"
    Mastodon = "@patrik@k8s.social"
    Gitlab = "sushi1903"
    Xing = "Patrik_Koptik"

  [params.footer]
    enable = true
    # Hier definierst du, was neben der Jahreszahl stehen soll
    author = "Patrik Koptik"
    # Zeigt das Startjahr bis heute an (z.B. 2021 - 2026)
    since = 2026
    # Zusätzlicher Text (Custom HTML möglich!)
    custom = "All rights reserved. If not stated otherwise."
    copyright = true

[languages]
  [languages.de]
    weight = 1
    languageCode = "de-de"
    languageName = "Deutsch"
    title = "Patrik Koptik"
    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "experience"
        pre = "<i class='fa-solid fa-briefcase'></i>"
        name = "Erfahrung"
        url = "/experience/"
        weight = 1
      [[languages.de.menu.main]]
        identifier = "techstack"
        pre = "<i class='fa-solid fa-code'></i>"
        name = "Tech Stack"
        url = "/techstack/"
        weight = 2
      [[languages.de.menu.main]]
        identifier = "posts"
        pre = "<i class='fa-solid fa-pen-nib'></i>"
        name = "Beiträge"
        url = "/posts/"
        weight = 3
      [[languages.de.menu.main]]
        identifier = "contact"
        pre = "<i class='fa-solid fa-envelope'></i>"
        name = "Kontakt"
        url = "/contact/"
        weight = 4

  [languages.en]
    weight = 2
    languageCode = "en-us"
    languageName = "English"
    title = "Patrik Koptik"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "experience"
        pre = "<i class='fa-solid fa-briefcase'></i>"
        name = "Experience"
        url = "/experience/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "techstack"
        pre = "<i class='fa-solid fa-code'></i>"
        name = "Tech Stack"
        url = "/techstack/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "posts"
        pre = "<i class='fa-solid fa-pen-nib'></i>"
        name = "Posts"
        url = "/posts/"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "contact"
        pre = "<i class='fa-solid fa-envelope'></i>"
        name = "Contact"
        url = "/contact/"
        weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true