baseURL = 'https://www.patrikkoptik.de'
languageCode = 'de-de'
title = 'Patrik Koptik'
theme = 'FixIt'

# ADD THIS SECTION:
[author]
  name = "Patrik Koptik"

[params]
  version = "0.3.X"

  [params.home]
    [params.home.profile]
      enable = true
      title = "Patrik Koptik"
      subtitle = "Cloud Native & Platform Engineer | Kubernetes Enthusiast"
      typeit = true
      social = true

  [params.social]
    GitHub = "PatrikKoptik"
    Linkedin = "patrik-koptik-27a165258"
    Mastodon = "@patrik@k8s.social"
    Gitlab = "sushi1903"
    Xing = "Patrik_Koptik"

[languages]
  [languages.de]
    weight = 1
    languageCode = "de-de"
    languageName = "Deutsch"
    title = "Patrik Koptik"
    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "posts"
        name = "Beiträge"
        url = "/posts/"
        weight = 1

  [languages.en]
    weight = 2
    languageCode = "en-us"
    languageName = "English"
    title = "Patrik Koptik"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" # Ein klassischer Dark-Mode Style für Code