baseURL = 'https://patrikkoptik.github.io/'
languageCode = 'en-us'
title = 'Patrik Koptik'
theme = 'congo'

# ADD THIS SECTION:
[author]
  name = "Patrik Koptik"

[params]
  # Theme color scheme: 'emerald', 'blue', 'slate', etc.
  colorScheme = "slate"
  # Layout options
  layoutWidth = "max-w-4xl"
  description = "Senior Developer Portfolio"

# Congo specifically checks this to avoid the warning error
[params.author]
  name = "Patrik Koptik"
  # image = "profile.jpg"
  headline = "Platform Engineer"
  bio = "I am a Platform Engineer working on Kubernetes and Cloud Native technologies."
  links = [
      { github = "https://github.com/PatrikKoptik" }
  ]

[params.header]
  layout = "fixed" # Keeps the nav at the top

[params.homepage]
  layout = "profile" # The "About Me" focus you wanted
  showRecent = true

[params.footer]
  showCopyright = true