baseURL = 'https://www.patrikkoptik.de'
languageCode = 'en'
title = 'Patrik Koptik'
theme = 'LoveIt'

# ADD THIS SECTION:
[author]
  name = "Patrik Koptik"

[params]
  # Standard-Farbschema ("light", "dark", "auto")
  defaultTheme = "auto"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

  [params.footer]
    enable = true
    copyright = true
    author = true
    since = 2026

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.png" # Bild in /static/images/ ablegen
      title = "Home"
      subtitle = "Cloud Native & Platform Engineer | Kubernetes Enthusiast"
      typeit = true # Schicker Schreibmaschinen-Effekt
      social = true

  [params.social]
    GitHub = "PatrikKoptik"
    Linkedin = "patrik-koptik-27a165258"
    Mastodon = "@patrik@k8s.social"
    Gitlab = "sushi1903"
    Xing = "Patrik_Koptik"

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1